language: ruby
install:
  - git clone https://github.com/thinca/vim-themis
  - git clone https://github.com/vim-jp/vital.vim
  - git clone https://github.com/lambdalisue/vital-System-Cache-Simple
  - git clone https://github.com/lambdalisue/vital-System-Cache-File
script:
  - vim --version
  - vim --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit
  - vim-themis/bin/themis --reporter spec --runtimepath vital.vim --runtimepath vital-System-Cache-Simple --runtimepath vital-System-Cache-File

